### ISSUE TITLE
Consider committing CSV data to github

### ISSUE THREAD

**Issue by rufuspollock** [alephdata/opensanctions#4]
Its not too big after all ;-)

Makes it nice to track over time etc.

**Comment by pudo** [comment]
Now uploading to archive.org for permanent storage, which seems more appropriate: https://archive.org/details/opensanctions

**Comment by rufuspollock** [comment]
But do you get diffs and pull requests?

Also what about uploading to https://datahub.io 😄 - just install data tool from https://datahub.io/download and do `data push` ...

**Comment by pudo** [comment]
will upload to datahub ;) -- but I'm not quite sure of what the meaning of a PR or a diff against a sanctions list would be: it would have to come from the authority publishing the sanctions data, otherwise it's .... "just, like, your opinion, man"?

One thing we do need to do is start to create a link list between the lists (i.e. "the Saddam Hussein on this list is the same as the Saddam on that list") -- are you aware of any good tools we should look at for that?

**Comment by rufuspollock** [comment]
@pudo 

> will upload to datahub ;) -- but I'm not quite sure of what the meaning of a PR or a diff against a sanctions list would be: it would have to come from the authority publishing the sanctions data, otherwise it's .... "just, like, your opinion, man"?

What i mean is you'd at least be able to track changes over time via the diffs and can see errors -- i've found this super useful with the core data stuff

Of course, the changes will still be the maintainers opinion (at least until point that the authoritative body starts doing PRs :wink:)

Let me know when on datahub.io 😄 

>  One thing we do need to do is start to create a link list between the lists (i.e. "the Saddam Hussein on this list is the same as the Saddam on that list") -- are you aware of any good tools we should look at for that?

Hmmm. Depends on tools vs patterns. And you may be more expert here - this is a classic "master data" plus match algorithm scenario as i understand it. If that is right we could then look for tools in that space.
