### ISSUE TITLE
us_ofac crawler breaks

### ISSUE THREAD

**Issue by haarts** [alephdata/opensanctions#66]
When running the `us_ofac` crawler it breaks along the way with a `KeyError` during the parse stage. The message is '345'. 
I have looked into this file: https://www.treasury.gov/ofac/downloads/sanctions/1.0/sdn_advanced.xml now contains a new 'featuretype'. with the ID 345, crashing the crawler (I suspect 344 is new too.)

I'm filing an issue instead of a PR since I'm a bit of a newbie when it comes to debugging and fixing the crawlers. Maybe you can help me? What I've done:
1. `clone repo`
1. `docker-compose up`
1. `docker-compose run worker ash`
1. `memorious --debug run us_ofac`

Now at the last step I do NOT see output from the `us_ofac` crawler but a snippet of the other crawlers running. In the terminal in which I ran `docker-compose up` I DID see some OFAC related output.

It feels I'm not doing it right.

**Comment by sunu** [comment]
Hi, a possible fix for the us_ofac issue is available in https://github.com/alephdata/opensanctions/pull/59. I just haven't had the time to test and merge it.

The output from other crawlers is probably due to the scheduler starting some of the other crawlers automatically. If you set `MEMORIOUS_DEBUG` to True on the worker container in the docker-compose.yaml file, that should stop the scheduler from running crawlers automatically.
